version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.30
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=auth
      - MYSQL_USER=test
      - MYSQL_PASSWORD=testUser
      - MYSQL_ROOT_PASSWORD=testUser
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci