spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: test
    password: testUser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
  data:
    redis:
      host: redis.jaeung.dev
      port: 6379
      repositories:
        enabled: false

jwt:
  secret: this_is_token_secret_code_please_replace_this_in_production