spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db.jaeung.dev:5432/postgres
    username: quid
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  data:
    redis:
      host: redis.jaeung.dev
      port: 6379
      repositories:
        enabled: false

jwt:
  secret: this_is_token_secret_code_please_replace_this_in_production